### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyCustomEnchantsShop#1]
* - [x] Shops
  * - [x] Shop Signs
    * - [x] Implemented
    * - [x] Permissions
      * - [x] Breaking
      * - [x] Creating
      * - [x] Using
    * - [x] Errors on Signs
      * - [x] Invalid enchantment
      * - [x] Missing values
      * - [x] You are not allowed to do this.
  * - [x] Shop UI
* - [ ] Language System
  * - [ ] Implementation
  *  - [ ] Languages
     * - [ ] English
     * - [ ] Spanish
     * - [ ] French
     * - [ ] Russian
     * - [ ] Chinese

**Comment by QuiverlyRivalry** [comment]
Instead of signs, why not use a UI?

**Comment by coolkidsrule101** [comment]
Yeah signs are so past and old we could use slapper to add the command cshop use that name for command for players

**Comment by DaPigGuy** [comment]
That's like saying commands are old and use Slappers instead...

**Comment by QuiverlyRivalry** [comment]
I think, to keep PiggyCE advanced use UIs, not signs.

**Comment by PotatoeTrainYT** [comment]
UI's are ugly tho, it removes the block theme from minecraft

**Comment by DaPigGuy** [comment]
Well in that case, time to strip commands from PiggyCE 🤦‍♂️

**Comment by PotatoeTrainYT** [comment]
nuu don't pig

**Comment by QuiverlyRivalry** [comment]
Its about time, we cant live on commands,, when UIs exist

**Comment by jrodr10** [comment]
Commands came before slappers Lol so Technically Commands are the most abstract of all 3 options

**Comment by PotatoeTrainYT** [comment]
but without commands u can't use slappers, its more work using slappers that signs like u lazy prats can't write signs

**Comment by QuiverlyRivalry** [comment]
No..
We need a UI, we cant live in the past with commands and signs.
Itll make PiggyCE seem old.

**Comment by PotatoeTrainYT** [comment]
no, uis ruins the blocky point of mc

**Comment by QuiverlyRivalry** [comment]
Blocky Point? Its the way forward.. every shop plugin switched to UIs, all big servers use ShopUIs, no more signs

**Comment by PotatoeTrainYT** [comment]
BrandPE is a big server, we are using signs

**Comment by QuiverlyRivalry** [comment]
What... you gave me a phar of your shopui xD

**Comment by jrodr10** [comment]
UI's prevent dupes, ETC

**Comment by QuiverlyRivalry** [comment]
Yep, signs, also cause lag.

**Comment by jrodr10** [comment]
He can do UIs and Signs instead if just one. It will make the plugin slightly bigger but its worth it

**Comment by coolkidsrule101** [comment]
Bruh UI are better than signs for one everyone loves it and that we could have something more advance then sign . Dude get out of 2014 and 2015 and get with 2017

**Comment by BurritoMan46** [comment]
Please just do it with UI everyone hate signs

**Comment by QuiverlyRivalry** [comment]
@DaPigGuy do UIs lol

**Comment by PotatoeTrainYT** [comment]
i love signs

**Comment by DaPigGuy** [comment]
Stop spamming the same things and look at the todo list first 🤦‍♂️

**Comment by DaPigGuy** [comment]
Removed the spam & unlocking the issue.

**Comment by Artistic-Waffle** [comment]
what the commands

**Comment by Artistic-Waffle** [comment]
it set to false in plugin yml

**Comment by DaPigGuy** [comment]
/ceshop is the command. It is only registered if UI shops are enabled

**Comment by Artistic-Waffle** [comment]
oh in custom enchants phar

**Comment by FaanMaario** [comment]
Can you, if possible, add a description for the enchantment when selecting it?
