### ISSUE TITLE
UI is empty

### ISSUE THREAD

**Issue by WeazyMC** [DaPigGuy/PiggyCustomEnchantsShop#12]
When I add an enchant nothing is displayed

--> isoz: "Nothing happens when I press the enchant I want to buy in the UI, just closes, no errors."

**Comment by Scali3n** [comment]
I have the same problem

**Comment by DaPigGuy** [comment]
This seems to be a client issue. When clients respond to a SimpleForm, the packet they send contains an empty data array.

**Comment by DaPigGuy** [comment]
Fixed.
