### ISSUE TITLE
[Help] How to make a custom enchant sign shop

### ISSUE THREAD

**Issue by Adam1609** [DaPigGuy/PiggyCustomEnchantsShop#13]
I have no clue on this, please help me

**Comment by Aericio** [comment]
It's UI, not sign.

**Comment by Adam1609** [comment]
i know it is UI, but you still keep that Sign in the code section.....

**Comment by Aericio** [comment]
My mistake, sign shop is default. I am not too sure how the sign is supposed to be setup since I've never used it. @DaPigGuy please answer.

**Comment by Adam1609** [comment]
rarely did I use UI for my server, so I ask to see if anybody know how to make a sign

**Comment by DaPigGuy** [comment]
```yml
ce
enchantment
level 
price
```
