### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by RubyTemple** [DaPigGuy/PiggyCustomEnchantsShop#18]
[16:31:31] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine
\item\enchantment\Enchantment::getEnchantment() must be of the type integer, str
ing given, called in /root/test2/StartPmmp/plugins/PiggyCustomEnchantsShop/src/D
aPigGuy/PiggyCustomEnchantsShop/Commands/CustomEnchantShopCommand.php on line 56
" (EXCEPTION) in "src/pocketmine/item/enchantment/Enchantment" at line 154

**Comment by RubyTemple** [comment]
ui shop not work

**Comment by RubyTemple** [comment]
[17:51:22] [Server thread/CRITICAL]: InvalidArgumentException: "Array size must 
be 4!" (EXCEPTION) in "src/pocketmine/event/block/SignChangeEvent" at line 86

**Comment by Aericio** [comment]
send your configuration

**Comment by Aericio** [comment]
> [17:51:22] [Server thread/CRITICAL]: InvalidArgumentException: "Array size must
be 4!" (EXCEPTION) in "src/pocketmine/event/block/SignChangeEvent" at line 86

caused by what? first error to this error seem unrelated
