### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by pranavbhuv** [DaPigGuy/PiggyCustomEnchantsShop#2]
Instead of PiggyCE using FormsAPI, or formsapi branch from PMMP. It be cool if it has its inbuilt library. This will help in the future, in adding more UIs feature. For example a new command possible like:
/cecreate
I know I suggested this before *winks*

**Comment by DaPigGuy** [comment]
Please STOP asking for forms. This WILL BE DONE SOON.
