### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by darkadams** [DaPigGuy/PiggyCustomEnchantsShop#22]
When I do /ceshop add lifesteal 1 10000 and when I enter it. It says internal server basically it crashes my game. Then when i do /ceshop add it opens a ui and i put enchant and lvl and then money and when i enter it nothing happens. I love ur plugins and I hope you can help me

**Comment by DaPigGuy** [comment]
Please do /ver PiggyCustomEnchantsShop & show results

**Comment by DaPigGuy** [comment]
Also please send any errors

**Comment by darkadams** [comment]
Ok I will see this error I got

**Comment by DaPigGuy** [comment]
Please respond within the next 24 hours or this issue will be closed
