### ISSUE TITLE
there no commands

### ISSUE THREAD

**Issue by Artistic-Waffle** [DaPigGuy/PiggyCustomEnchantsShop#3]

**Comment by TwistedAsylumMC** [comment]
there isn't supposed to be, its all on signs just follow the format i type below on a sign

[CE]
ce name
ce level
cost

example:
[CE]
poison
1
1
(poison level 1 for $1)

**Comment by Artistic-Waffle** [comment]
That the most stupid thing I ever heard . no one use signs any more wow

**Comment by TwistedAsylumMC** [comment]
lol make ur own ui for it then

**Comment by Artistic-Waffle** [comment]
I don't get how dapigguy can't make book. I don't think he can make book

**Comment by TwistedAsylumMC** [comment]
what

**Comment by Artistic-Waffle** [comment]
.... Ugh I just make my plugin that turns his enchants to books

**Comment by TwistedAsylumMC** [comment]
u can :/ enchant a book then u can apply it to tools etc

**Comment by Artistic-Waffle** [comment]
......

**Comment by Artistic-Waffle** [comment]
Aye I got a question is minenet better hub software or pocketmine or nukkit

**Comment by TwistedAsylumMC** [comment]
pmmp

**Comment by Artistic-Waffle** [comment]
But it so laggy when people join

**Comment by TwistedAsylumMC** [comment]
thats not pmmp fault

**Comment by Artistic-Waffle** [comment]
True

**Comment by Artistic-Waffle** [comment]
Well thank for the help ik that one day I start a channel and the making of my server
