### ISSUE TITLE
CE limit

### ISSUE THREAD

**Issue by minijaham** [DaPigGuy/PiggyCustomEnchantsShop#31]
### Description
Duplicate of DaPigGuy/PiggyCustomEnchants#261 , but I wanted to make my point clear. I am currently the owner of a server, which I am currently developing on and I was looking for a custom enchantment plugin because I did not want to code a whole different CE core .-.(great plugin btw, I love it)

I definitely need a feature that which sets a limit on the number of CEs that can be enchanted on an item(can be configured in config), because having more than 8 CEs make the item very overpowered, even the working chances of the enchantments are lowered down in the config.

If you can't update the plugin furthermore with this feature being added, please consider at least telling me how to try to add the feature to the plugin(by coding extra stuff in) because I've tried it multiple times and all of them...yeah I messed it up lol

Thanks! Also be careful of corona! 

Also for springs and gears(actually, all helpful effects), will it be possible so that I can configure the levels that you get when wore?

**Comment by minijaham** [comment]
oh shoot wrong github link lol sorry
I was gonna put this in the CustomEnchants not the shop

**Comment by Thunder33345** [comment]
> oh shoot wrong github link lol sorry
I was gonna put this in the CustomEnchants not the shop

Learn to read previous reply, even you said it's a duplicate. Why not try to read the previous response?

> You're better off having the limit on what's applying the enchants instead of directly in the core, seems kind of pointless here

it WILL NOT be added to the core
it does not make sense to be added in the core
if your enchanting plugin does not support limits, go nag them in the correct place, not piggyCE
