### ISSUE TITLE
Levels with limiters

### ISSUE THREAD

**Issue by pleasepoggitwork** [DaPigGuy/PiggyCustomEnchantsShop#32]
Please make sure your issue complies with these guidelines:
- * [X] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [X] Issue must have not been reported previously
- * [X] Make sure you are on the latest version of PMMP & PiggyCustomEnchantsShop
- * [X] Have a detailed title (i.e "Can not create sign shops")

### Issue Description

- Expected result: What were you expecting to happen?
When at the level cap, you should be ubale to upgrade an enchants level, if that enchant is on the item.
- Actual result: What actually happened?
When having ce limiters, if you are at the cap, and have say a backstab level 1 sword. The limiter wont allow you to enchant a higher level of that enchant.
#### Steps to Reproduce the Issue
1. ... Get any item to the ce limiter cap
2. ... Try to make a level 1 enchant higher

### OS and Versions

* PocketMine-MP:
* PiggyCustomEnchantsShop:
* PHP:
* Server OS:

### Extra Information

**Comment by DaPigGuy** [comment]
You can increase the max levels within PiggyCE.
