### ISSUE TITLE
Ban World

### ISSUE THREAD

**Issue by mrpwes** [DaPigGuy/PiggyCustomEnchantsShop#34]
config.yml

This is Used to Ban Commands in only the Worlds Below.
Worlds: ["bannedworld1", "bannedworld2"] # You can add as Many as needed

~~Like CustomShopUI

**Comment by Aericio** [comment]
re: https://github.com/DaPigGuy/PiggyCustomEnchants/issues/317#issuecomment-662767437

If the enchantment is disabled, then even if they buy it, the enchant won't do anything. Otherwise, remove `/ceshop` permission from them and use signs instead.
