### ISSUE TITLE
Enchant Table

### ISSUE THREAD

**Issue by DebHugo** [DaPigGuy/PiggyCustomEnchantsShop#35]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description
Add the possibility of being able to open the shop by clicking on the enchantment table

### Extra Information

**Comment by Aericio** [comment]
Get a plugin that runs a command when a block is it, like TapToDo if that still works.
