### ISSUE TITLE
protection

### ISSUE THREAD

**Issue by nasiridrishi** [DaPigGuy/PiggyCustomEnchantsShop#5]
shop doesn't work for player in world protection or area protected by iprotect . to make it work with area protected by iprotect i have to flag touch but there is no solution for world protection. tbh and other plugins like economyshop work with no problem under same conditions!

**Comment by optimusprime338** [comment]
Talking abt UI yes this plugin needs it badly! why not just remove UI from main plugin and add that here!! and it needs it coz on windows 10 when you right click holding armors you actually wear it! well its kinda annoying when you have to tap 2 times 2 buy an enchant but cant lol.. other solution is player have already a armor on then which is not a good solution actually annoying ..
Thanks!
