### ISSUE TITLE
FIX!

### ISSUE THREAD

**Issue by amarigamer10** [DaPigGuy/PiggyCustomEnchantsShop#7]
umm the shop ui dosnt work i do /ceshop dosnt work i dont even see a command coming up can u fix please

**Comment by DaPigGuy** [comment]
You must turn shop-type to UI to enable UI shop and /ceshop.

**Comment by amarigamer10** [comment]
Okay thanks and u reply fast lmao :) and is there anyway we can dm Twitter
discord?

**Comment by DaPigGuy** [comment]
Discord Server is https://discord.gg/XUHAEWg

Twitter is @dapigguy but I'm rarely active on Twitter.

**Comment by amarigamer10** [comment]
Ik ur twitter I already follow u :) and the UI still don't work
