### ISSUE TITLE
command shop UI

### ISSUE THREAD

**Issue by llronaldoll** [DaPigGuy/PiggyCustomEnchantsShop#8]
is the command to open a UI store?

**Comment by DaPigGuy** [comment]
The command is /ceshop. It is only registered when you set shop-type to ui in config.yml and install FormAPI at https://github.com/jojoe77777/FormAPI

**Comment by llronaldoll** [comment]
How do I create a shop with vanilla enchant?

**Comment by Aericio** [comment]
Currently, you cannot do that. It only works for PiggyCE's custom enchants.

**Comment by llronaldoll** [comment]
can you tell me a plugin that looks good just like piggy to vanilla enchant?

**Comment by Aericio** [comment]
unknown.
