### ISSUE TITLE
the config file does not appear

### ISSUE THREAD

**Issue by brexmania123** [DaPigGuy/PiggyCustomEnchantsShop#9]
HI so i have downloaded the plugin today and followed the step by step instructions for the Installation here https://dapigguy.github.io/PiggyCustomEnchantsShop/, but this location /plugins/PiggyCustomEnchantsShop/config.yml does not exist. i tried adding it myself but that only broke the server. can you please fix

**Comment by Aericio** [comment]
Did you install PiggyCustomEnchants and PiggyCustomEnchantsShop?

**Comment by DaPigGuy** [comment]
Also make sure you have EconomyAPI.
